---
- name: Enable "{{ item.kernel_param_name }}"
  sysctl:
    name: "{{ item.kernel_param_name }}"
    reload: false
    state: present
    value: "{{ item.kernel_param_value }}"
  with_items: "{{ kernel_params }}"
