---
- become: true
  name: Converge
  hosts: all
  vars:
    kernel_params:
      - kernel_param_name: net.ipv4.tcp_fastopen
        kernel_param_value: 3
      - kernel_param_name: net.ipv4.tcp_max_syn_backlog
        kernel_param_value: 8192
      - kernel_param_name: fs.inotify.max_user_watches
        kernel_param_value: 524288
  roles:
    - role: ansible-role-sysctl
