---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian10
    image: debian:10
  - name: rhel8
    image: centos:8
  - name: suse15
    image: opensuse/leap
provisioner:
  name: ansible
verifier:
  name: testinfra
